name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Install Google Chrome
      run: |
        choco install googlechrome --ignore-checksums -y

    - name: Install ChromeDriver
      run: |
        choco install chromedriver --ignore-checksums -y
        setx path "%path%;C:\Program Files (x86)\Google\Chrome\Application"
        setx path "%path%;C:\tools\chromedriver"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      env:
        HEADLESS: true
      run: dotnet test --configuration Release --framework net8.0 --verbosity normal --settings test.runsettings
